name: Trigger Theme Build

on:
  push:
    branches: [astro]
  workflow_dispatch:

jobs:
  dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Dispatch build event to theme repository
        env:
          DISPATCH_TOKEN: ${{ secrets.DISPATCH_TOKEN }}
        if: ${{ env.DISPATCH_TOKEN != '' }}
        uses: peter-evans/repository-dispatch@v4
        with:
          token: ${{ env.DISPATCH_TOKEN }}
          repository: needhourger/Shirone # 请替换为你的主题代码仓路径
          event-type: content-updated
          client-payload: >-
            {"sha": "${{ github.sha }}", "ref": "${{ github.ref }}", "repo": "${{ github.repository }}"}